### ISSUE TITLE
Does Marker icon need to be an AssetImage?

### ISSUE THREAD

**Issue by gcsaba2** [liodali/osm_flutter#197]
I have an image which I want to display on the map.

This works:
```dart
var _image = MarkerIcon(image: AssetImage("assets/myimage.png"));
_mapController.addMarker(GeoPoint(
    latitude: _lat,
    longitude: _lon
), markerIcon: _image
```

The problem is, I need to scale the image. This can be done with:

```dart
var _image = MarkerIcon(image: Image.asset("assets/myimage.png", scale: 0.5));
```

Unfortunately, the MarkerIcon requires an object of type AssetImage and Image.asset() does not return an `AssetImage`.

Is there a reason why the MarkerIcon needs to use an AssetImage? Can't it just use `AssetBundleImageProvider` or even better, `ImageProvider`?

**Comment by liodali** [comment]
i did that because, it will make render fast, beause i render the widget before i send it to native view to be shown in the map, but i will see what i can improve and i will make test to know if we have any problem to render that
but  my advice for now try to make you images as icons it will be better for all cases and fast in rendering also

**Comment by liodali** [comment]
in the next version, i added `assetMarker` that you can make change scale or color for asset image

**Comment by gcsaba2** [comment]
Thank you
